default: &default
   adapter: postgresql
   encoding: unicode
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   host: postgres
   user: postgres

development:
  <<: *default
  database: note_docker_development

test:
  <<: *default
  database: note_docker_test

production:
  <<: *default
  database: note_docker_production