# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9898fc62853fa5250ddd75557fc0a4806653f37a3c16702f622d4688d7df8397b378a6245d24eaed692f47c2fe234e75f7465539f62b1ce9c56b0770a5e026c

test:
  secret_key_base: 76193c6c0b1748e681c67cf2ef9865fd7d03fc1f18b2cd97529ad33c4a54f74276b5f1db8f482e9a5b0f925eadbe2bdd027484e23ac3ab2b34939af82cf990ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
